"""Acciones de auditoría (valores cortos, sin secretos)."""

LOGIN_OK = "LOGIN_OK"
LOGIN_FALLIDO = "LOGIN_FALLIDO"
LOGIN_BLOQUEADO = "LOGIN_BLOQUEADO"
USUARIO_CREADO = "USUARIO_CREADO"
USUARIO_EDITADO = "USUARIO_EDITADO"
USUARIO_ACTIVADO = "USUARIO_ACTIVADO"
USUARIO_DESACTIVADO = "USUARIO_DESACTIVADO"
PEDIDO_ABIERTO = "PEDIDO_ABIERTO"
COMANDA_ENVIADA = "COMANDA_ENVIADA"
PRECUENTA = "PRECUENTA"
COBRO = "COBRO"
CANCELACION = "CANCELACION"
FORMA_PAGO = "FORMA_PAGO"
PUNTOS_AJUSTE = "PUNTOS_AJUSTE"
GASTO_CREADO = "GASTO_CREADO"
GASTO_ELIMINADO = "GASTO_ELIMINADO"
ID_USUARIO_DISCREPANCIA = "ID_USUARIO_DISCREPANCIA"
ADMIN_SENSIBLE = "ADMIN_SENSIBLE"

DETALLES_PROHIBIDOS = frozenset(
    {
        "password",
        "hash_password",
        "access_token",
        "token",
        "authorization",
        "secret",
        "secret_key",
        "refresh_token",
    }
)
